me: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-22.04' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      # Uses global.json to determine SDK version
      uses: actions/setup-dotnet@v4.0.1
    - name: Install Ubuntu dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update &&
        sudo apt-get install -y tesseract-ocr libleptonica-dev && 
        ls -la /usr/local/lib && 
        ls -la /usr/lib/x86_64-linux-gnu
    - name: Install dependencies
      run: dotnet restore src/Tesseract.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/Tesseract.sln
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger trx --results-directory "TestResults" src/Tesseract.sln
